if "https://i.imgur.com/WFJSU4l.gifv"[-4:-1] + "v" == "gifv":
    print(True)
else:
    print(False)

print("https://i.imgur.com/WFJSU4l.gifv"[:-5])
"""


import csv

message = input("> ")
a = message.replace("", "||||")
a = a[2:-2]
print(a)
lyrics = ["Se no!",
"Demo sonnan ja dame",
"Mou sonnan ja hora",
"Kokoro wa shinka suru yo",
"Motto motto",
"",
"Kotoba ni sureba kiechau kankei nara",
"Kotoba o keseba ii ya tte",
"Omotteta osoreteta",
"Dakedo are? nanka chigau kamo...",
"Senri no michi mo ippo kara!",
"Ishi no you ni katai sonna ishi de",
"Chiri mo tsumoreba Yamato Nadeshiko?",
"'shi' nuki de iya shinu ki de!",
"",
"Fuwafuwari fuwafuwaru",
"Anata ga namae o yobu",
"Sore dake de",
"Chuu e ukabu",
"Fuwafuwaru fuwafuwari",
"Anata ga waratte iru",
"Sore dake de",
"Egao ni naru",
"",
"Kami-sama arigatou",
"Unmei no itazura demo",
"Meguriaeta koto ga",
"Shiawase na no",
"",
"Demo sonnan ja dame",
"Mou sonnan ja hora",
"Kokoro wa shinka suru yo",
"Motto motto",
"Sou sonnan ja ya da",
"Nee sonnan ja mada",
"Zutto zutto",
"Watashi no koto mitete ne",
"",
"Watashi no naka no anata hodo",
"Anata no naka no watashi no sonzai wa",
"Madamada ookikunai koto mo",
"Wakatteru keredo",
"Ima kono onaji shunkan",
"Kyouyuu shiteru jikkan",
"Chiri mo tsumoreba Yamato Nadeshiko!",
"Ryakushite? chiri-tsumo Yamato Nadeko!",
"",
"Kurakurari kurakuraru",
"Anata o miagetara",
"Sore dake de",
"Mabushisugite",
"Kurakuraru kurakurari",
"Anata o omotte iru",
"Sore dake de",
"Tokete shimau",
"",
"Kami-sama arigatou",
"Unmei no itazura demo",
"Meguriaeta koto ga",
"Shiawase na no",
"",
"KO I SU RU KI SE TSU WA YO KU BA RI Circulation",
"KO I SU RU KI MO CHI WA YO KU BA RI Circulation",
"KO I SU RU HI TO MI WA YO KU BA RI Circulation",
"KO I SU RU O TO ME WA YO KU BA RI Circulation",
"",
"Fuwafuwari fuwafuwaru",
"Anata ga namae o yobu",
"Sore dake de",
"Chuu e ukabu",
"Fuwafuwaru fuwafuwari",
"Anata ga waratte iru",
"Sore dake de",
"Egao ni naru",
"",
"Kami-sama arigatou",
"Unmei no itazura demo",
"Meguriaeta koto ga",
"Shiawase na no",
"",
"Demo sonnan ja dame",
"Mou sonnan ja hora",
"Kokoro wa shinka suru yo",
"Motto motto",
"Sou sonnan ja ya da",
"Nee sonnan ja mada",
"Watashi no koto mitete ne",
"Zutto zutto"]
"""